### ISSUE TITLE
TypeError: _.extend is not a function

### ISSUE THREAD

**Issue by majidhassan** [sebsylvester/parse-server-mailgun#1]
Hey,

I've bee using this adapter for my emails with parse-server hosted on DigitalOcean. It's been working fine, until today with a fresh parse-server installation I started getting the following error:

```
parse-server-wrapper-0 TypeError: _.extend is not a function
parse-server-wrapper-0     at Object.<anonymous> (/usr/lib/node_modules/parse-server-mailgun/node_modules/cheerio/lib/cheerio.js:88:3)
parse-server-wrapper-0     at Module._compile (module.js:409:26)
parse-server-wrapper-0     at Object.Module._extensions..js (module.js:416:10)
parse-server-wrapper-0     at Module.load (module.js:343:32)
parse-server-wrapper-0     at Function.Module._load (module.js:300:12)
parse-server-wrapper-0     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
parse-server-wrapper-0     at Module.require (module.js:353:17)
parse-server-wrapper-0     at require (internal/module.js:12:17)
parse-server-wrapper-0     at Object.<anonymous> (/usr/lib/node_modules/parse-server-mailgun/node_modules/cheerio/index.js:5:28)
parse-server-wrapper-0     at Module._compile (module.js:409:26)
```

This is my ecosystem.json run with pm2.

```
{
  "apps" : [{
    "name"        : "parse-server-wrapper",
    "script"      : "/usr/bin/parse-server",
    "watch"       : false,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": dburi",
      "PARSE_SERVER_APPLICATION_ID": "appid",
      "PARSE_SERVER_MASTER_KEY": "masterkey",
      "PARSE_PUBLIC_SERVER_URL": "serverurl",
      "PARSE_SERVER_MOUNT_PATH": "/parse",
      "VERBOSE": "1",
      "PARSE_SERVER_APP_NAME": "appname",
      "PARSE_SERVER_VERIFY_USER_EMAILS": true,
      "PARSE_SERVER_EMAIL_ADAPTER": {
          "module": "parse-server-mailgun",
          "options": {
            "fromAddress": "noreply@example.com",
            "domain": "example.com",
            "apiKey": "key-apikey",
            "templates": {
              "passwordResetEmail": {
                "subject": "Reset your password",
                "pathPlainText": "/usr/lib/node_modules/parse-server/public_html/password_reset_email.txt",
                "pathHtml": "/usr/lib/node_modules/parse-server/public_html/password_reset_email.html"
              },
              "verificationEmail": {
                "subject": "Confirm your account",
                "pathPlainText": "/usr/lib/node_modules/parse-server/public_html/verification_email.txt",
                "pathHtml": "/usr/lib/node_modules/parse-server/public_html/verification_email.html"
              }
            }
          }
      },
      "PARSE_SERVER_PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL": true
    }
  }, {
    "name"        : "parse-dashboard-wrapper",
    "script"      : "/usr/bin/parse-dashboard",
    "watch"       : false,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
    ... dashboard stuff
    }
  }]
}
```

Environment:

parse-server 2.217
parse-server-mailgun 1.0.2

**Comment by sebsylvester** [comment]
Hi, I've tested it locally with the latest version of parse-server, and I can not reproduce the error.
The issue seems to be related to lodash, a dependency of cheerio. Have you debugged it already, by setting a breakpoint on line 88 of cheerio.js? Perhaps the underscore that lodash uses is overwritten. You could also try installing lodash seperately as a top level dependency. But it's hard for me to help you without being able to reproduce the error.

Regards,
Sebastian

**Comment by majidhassan** [comment]
Hey,

I tried installing lodash using `npm install -g lodash`. But it still doesn't work.

I also tried requiring lodash using the absolute path instead of relative path. I noticed, when printing the required lodash variable, that it contains no functions.

Output of printing _ is `{}` as opposed to printing the required parse variable as a comparison, which outputs: ` { [Function] evaluate: [Function], update: [Function] }`.

The currently installed cheerio version is `cheerio@0.20.0` and lodash `lodash@4.14.0`.

**Comment by majidhassan** [comment]
Alright, I see, that the required lodash package on cheerio is 4.1.0. Somehow I have 4.14.0 installed.

`cheerio@0.20.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.2.0, htmlparser2@3.8.3, jsdom@7.2.2, lodash@4.14.0)`

When reverting to lodash@4.1.0 it works fine. This happens in both cases, with `npm install parse-server-mailgun` and `npm install -g parse-server-mailgun`.

Any ideas how the installed package version could differ from the version specified in the package.json?

**Comment by sebsylvester** [comment]
Hi, I am no expert in how npm works internally but I think it's because so many other packages depend on lodash, it becomes a little unpredictable as to which version you end up with. Some packages, like parse-server, lock-in to a specific version and install it in their own node_modules directory. But usually, packages share the same dependency, as long their dependency requirements can be met by that single version.

**Comment by majidhassan** [comment]
Is the adapter running well with your lodash@4.14.0? Cause with, that's the version causing the trouble.

**Comment by sebsylvester** [comment]
Update:
I just tested parse-server-mailgun, with the latest version, and it works fine

**Comment by sebsylvester** [comment]
I think the culprit might be pm2. Unfortunately, I am not familiar with that.
Other than that, I am out of ideas...

**Comment by majidhassan** [comment]
Alright. For now what works - which, I know, is a REALLY dirty hack - is overwriting the lodash version for cheerio. Basically:

```
cd /usr/lib/node_modules/parse-server-mailgun/node_modules/cheerio/
npm install lodash@4.1.0
```

I haven't seen such a dirty hack in a long time.
