### ISSUE TITLE
peerDependencies issue

### ISSUE THREAD

**Issue by flavordaaave** [sebsylvester/parse-server-mailgun#11]
I just wanted to upgrade to the latest parse-server version 2.2.25-beta.1 and got following error:

```
npm ERR! peerinvalid The package parse-server@2.2.25-beta.1 does not satisfy its siblings' peerDependencies
```

**Comment by sebsylvester** [comment]
I removed the peer dependency. It should be ok now.
I think the error was caused by npm as a result of the "-beta.1" version suffix.
