### ISSUE TITLE
Template paths

### ISSUE THREAD

**Issue by JEKos** [sebsylvester/parse-server-mailgun#15]
Hi again,
Now I want to add the paths for my custom templates that I made. The path is  `myparse-server/node_modules/parse-server-mailgun/Custom_Reset_Password_Folder/index.html`.

How this path need to be written inside the index.js of my parse server?

**Comment by sebsylvester** [comment]
Hi, 
Just use the path.resolve function in the config object, as shown in the [readme.md](https://github.com/sebsylvester/parse-server-mailgun#adapter-configuration). Perhaps you need to read up on that function in the node.js docs.

**Comment by JEKos** [comment]
Could you give a example how can I to do this with the path I gave at the first post?

**Comment by JEKos** [comment]
This is the error that I'm getting when I am doing `npm start` with and the index.js has the templates options in it with the path `'password_reset_email.txt'` for txt ,and `'Custom_Reset_Password/index.html'` for html

```
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/myparse-server/npm-debug.log
```

**Comment by sebsylvester** [comment]
Check out this example from the module's test directory https://github.com/sebsylvester/parse-server-mailgun/blob/master/test/MailgunAdapter.js

**Comment by JEKos** [comment]
Yes!!! It works, thank for the example!
