### ISSUE TITLE
SyntaxError?

### ISSUE THREAD

**Issue by Meersad** [sebsylvester/parse-server-mailgun#17]
Hi, am i doing something wrong or is there some syntax error?

Using latest parse-server and it works with 'parse-server-simple-mailgun-adapter'

```javascript
emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
      fromAddress: 'noreply@email.com',
      domain: 'mydomain.com',
      apiKey: 'key-xxxxxx',
      templates: {
        passwordResetEmail: {
          subject: 'Reset your password',
          pathPlainText: resolve(__dirname, 'test/email-templates/password_reset_email.txt'),
          pathHtml: resolve(__dirname, 'test/email-templates/password_reset_email.html'),
          callback: (user) => { return { firstName: user.get('firstName') }}
        },
        verificationEmail: {
          subject: 'Confirm your account',
          pathPlainText: resolve(__dirname, 'test/email-templates/verification_email.txt'),
          pathHtml: resolve(__dirname, 'test/email-templates/verification_email.html'),
          callback: (user) => { return { firstName: user.get('firstName') }}
        },
        customEmailAlert: {
          subject: 'Urgent notification!',
          pathPlainText: resolve(__dirname, 'test/email-templates/custom_alert.txt'),
          pathHtml: resolve(__dirname, 'test/email-templates/custom_alert.html'),
        }
      }
    }
  }
```

> parse-server-example@1.4.0 start /opt/repo/ROOT
> node index.js

DATABASE_URI not specified, falling back to localhost.
/opt/repo/ROOT/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:24
constructor(options = {}) {
^

SyntaxError: Unexpected token =
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:404:25)
at Object.Module._extensions..js (module.js:432:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:313:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at loadAdapter (/opt/repo/ROOT/node_modules/parse-server/lib/Adapters/AdapterLoader.js:27:15)
at loadAdapter (/opt/repo/ROOT/node_modules/parse-server/lib/Adapters/AdapterLoader.js:34:12)
at new ParseServer (/opt/repo/ROOT/node_modules/parse-server/lib/ParseServer.js:279:65)

npm info lifecycle parse-server-example@1.4.0~start: Failed to exec start script
npm ERR! Linux 2.6.32-042stab120.11
npm ERR! argv "/opt/jelastic-nodejs5.1/bin/node" "/bin/npm" "start" "-d"
npm ERR! node v5.1.1
npm ERR! npm v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node index.js
npm ERR! You can get their info via:
npm ERR! npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /opt/repo/ROOT/npm-debug.log

**Comment by sebsylvester** [comment]
Hi, my mistake. The build target was not low enough, I've published a new build (2.3.5) that works with node v4.5+. So, the error should not occur anymore.
