### ISSUE TITLE
unable to use variables in subject for example {{appName}}

### ISSUE THREAD

**Issue by gowridev** [sebsylvester/parse-server-mailgun#18]
unable to use variables in subject of the mail, for example {{appName}}. could you please guide us in this regard.

**Comment by sebsylvester** [comment]
Hi, for the regular use cases like reset password and account confirmations, the use of variables in the subject is not supported. Variables can only be used in the message body. The subject will always be the value found in the adapter configuration.

For custom emails (not the password reset or new account emails) there is the ability to override the subject by providing it as an option. I hope this answers your question.
