### ISSUE TITLE
Should return the promise so that cloud code knows when the operation completes

### ISSUE THREAD

**Issue by dan-nyanko** [sebsylvester/parse-server-mailgun#2]
Hello,

There is a minor issue with the code that I noticed when sending mail.  The method `_sendMail()` does not return the promise upon resolving `this.mailgun.messages().sendMime()`.

Please see my PR.  Thanks!

**Comment by sebsylvester** [comment]
Hi, thanks for the PR. I haven't used the adapter directly from Cloud code, so it's cool you pointed this out.

**Comment by dan-nyanko** [comment]
For anyone interested, [example-parse-server](https://github.com/dan-nyanko/example-parse-server/) shows how to run parse-server as a nodejs express app and send an email via cloud code.
