### ISSUE TITLE
Is there any option for a callback?

### ISSUE THREAD

**Issue by peterpme** [sebsylvester/parse-server-mailgun#21]
Hey,

Love your module! 

I was looking through the code and I didn't see anything about a success / error callback. Is there anything I can use after running

`MailgunAdapter.send()` to see if it's been sent successfully or if there were some error?

If not, would you be open to a PR that adds this feature?

Thanks again! You rock!

**Comment by sebsylvester** [comment]
Hi, 
Nice to hear you like the module : )
To answer your question. ```MailgunAdapter.send()``` returns a Promise that wraps an async operation (the sending of the email), so you can register a success callback with the ```then``` method and an error handler with the ```catch``` method of the Promise.
Is this a useful reply?

**Comment by peterpme** [comment]
Thanks for the quick reply!

I had a feeling that was the case when I saw `co`, haha. 

Thanks for clearing it up :)
