### ISSUE TITLE
Mail tags & tracking options

### ISSUE THREAD

**Issue by mishachesnokov** [sebsylvester/parse-server-mailgun#24]
As I found - adapter doesn't support setting 'o:tags' & 'o:tracking' (-opens)
Am I mistaken? If so - what's the way to do it?

**Comment by sebsylvester** [comment]
I suppose you would need to add custom options to the [mailcomposer](https://www.npmjs.com/package/mailcomposer) function (which creates the MIME string). This is not currently supported.
