### ISSUE TITLE
BCC field not working in extras

### ISSUE THREAD

**Issue by enjoyjeremy** [sebsylvester/parse-server-mailgun#31]
I'm attempting to add two BCC email addresses through environment variables in the format `firstaddress@email.com,secondaddress@email.com` but it is not working. I checked the tests and it looks like this isn't covered. How can I see if this is working? Here's my code:

```
    return MailgunAdapter.send({
      templateName: 'receiptEmail',
      subject: 'Your order receipt',
      fromAddress: 'Sender <orders@sender.com>',
      recipient: billingAddress.email,
      variables: { 
        firstName: billingAddress.first_name,
        orderId: orderId
      },
      extra: {
        bcc: process.env.CUSTOMER_EMAIL_BCC
      }
    });
```

Thanks!

**Comment by sebsylvester** [comment]
I'm not sure if this works, but you could try to convert the string environment variable into an array like this: ```process.env.CUSTOMER_EMAIL_BCC.split(',')```.

**Comment by sebsylvester** [comment]
According to the Mailgun documentation (https://documentation.mailgun.com/en/latest/api-sending.html#sending), it is necessary to add cc and bcc addresses as recipients.
