### ISSUE TITLE
Mailgun Integration With Swift/Parse

### ISSUE THREAD

**Issue by fprospato** [sebsylvester/parse-server-mailgun#32]
In my project I want to implement two features: 
**1) Verify email confirmation during the sign up process.** 
**2) Reset password via email. I am coding in Swift 3 with Parse and I have a MailGun account.** 

I have a Mailgun account and have linked it to my and have an active domain running. But after this I do not know how to integrate this with my Xcode project that is fully coded in Swift using a Parser Server. The Mailgun website has set up instructions for the email confirmation but none of the code is in Swift and I do not know how to transfer it to Swift. This is the same for all of the other links and articles I have found on the internet. The only thing I have tried and has worked is just sending a normal email using:

```
    let mailgun = Mailgun.client(withDomain: "****.com", apiKey: "key-*****")
    
    mailgun?.sendMessage(to: "user *email*", from: "*connected email*", subject: "Verify Email address", body: "Thank for signing up! Please press the link below to verify your email address.")
```

But to have a verfy email and change password function, I need more than the standard text and have a link that connects to the server to validate the email and change the password. The only thing I know is that Parse has the `PFUser.requestPasswordResetForEmail` feature but I do not know how to properly connect my Mailgun to the project so when I try to run it I recieve the error: "An appName, publicServerURL, and emailAdapter are required for password reset functionality." 

**Any help given on any part of this is greatly appreciated as this is a problem for thousands of other Swift coders.** Thanks in advance!

**Comment by sebsylvester** [comment]
Hi, 
the error you mention is not raised by the `parse-server-mailgun` module. I found the error-raising code in the Parse Server's [UsersRouter module](https://github.com/parse-community/parse-server/blob/139b9e1cb33f97181ce913b201d176969016c70f/src/Routers/UsersRouter.js#L192). I can't tell you why this happens, but I would recommend that you ask this question to the Parse Server community, preferably with some project code.
Good luck!
