### ISSUE TITLE
An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.

### ISSUE THREAD

**Issue by Abderezai** [sebsylvester/parse-server-mailgun#33]
Hi,
I have the following setup

var api = new ParseServer({
  databaseURI: process.env.MONGODB_URI,
  cloud: __dirname + '/cloud/main.js',
  appId: process.env.APP_ID,
  masterKey: process.env.MASTER_KEY, 
  serverURL: process.env.SERVER_URL ,
  emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
      appName: 'MyAppName',
      fromAddress: 'MyApName <noreply@myappname.com>',
      // Your domain from mailgun.com 
      domain: 'myappname.com',
      // Your API key from mailgun.com 
      apiKey: 'key-##############',
      // The template section 
      templates: {
        passwordResetEmail: {
          subject: 'Reset your password',
          pathPlainText: resolve(__dirname, 'email/PasswordReset.txt'),
          pathHtml: resolve(__dirname, 'email/PasswordReset.html'),
          callback: (user) => { return { firstName: user.get('username') }}
        }
      }
    }
  }
});

When attempting to reset password I get following error from parse:
An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.

But I think I have set all these things. Thanks

**Comment by sebsylvester** [comment]
Hi,
It seems like you haven't included the `publicServerURL` parameter in the snippet above.
If that does not solve the problem, check out [this link](https://github.com/parse-community/parse-server/blob/139b9e1cb33f97181ce913b201d176969016c70f/src/Routers/UsersRouter.js#L192) to the source file that throws the error. My suggestion would be to start a debugging session at that point.

**Comment by Abderezai** [comment]
is the public server url process.env.SERVER_URL (i.e) myapp.com/parse ?
Thanks a ton

**Comment by sebsylvester** [comment]
That's correct. You should also prefix the url with http or https.

**Comment by amitkh6** [comment]
@Abderezai  Can you teach me how did you set it up, I tried doing it but not able to .
