### ISSUE TITLE
can't open attached files

### ISSUE THREAD

**Issue by scheichi** [sebsylvester/parse-server-mailgun#37]
### Code
I **tried** to send a .pdf file using this config

```javascript
var filePath = path.join(res.filename);
var data = fs.readFileSync(filePath);

MailgunAdapter.send({
    templateName: 'testTemplate',
    subject: 'Subject',
    fromAddress: 'From Address <from@address.com>',
    recipient: request.object.get("email"),
    variables: {
        variables: "variables"
    },
    extra: {
        attachments: [data]
    }
})
```

if i send the same things with the **mailgun-js** function it is working

```javascript
var filePath = path.join(res.filename);
var data = fs.readFileSync(filePath);

var data = {
    fromAddress: 'From Address <from@address.com>',
    recipient: request.object.get("email"),
    subject: 'Hello',
    text: 'Testing some Mailgun awesomeness!',
    attachment: data
};

mailgun.messages().send(data, function(error, body) {
    console.log(body);
})
```

i've also tried to send it via the **Attachment Object** of mailgun-js
```javascript
var filePath = path.join(res.filename);
var data = fs.readFileSync(filePath);
var filename = 'test.pdf';

var attch = new mailgun.Attachment({
    data,
    filename,
    contentType: 'application/pdf'
}); 
```

again it worked for the mailgun-js .send() function but not for the MailgunAdapter .send()

## Mailgun Dashboard Logs
Every File which was sent by **MailgunAdapter** seemed to be empty. I've checked the logs in the **mailgun dashboard** and the filesize was just few bytes. For the mails sent via mailgun-js were the same values just the size and name were different:

**mailgun-js**
(if i sent it just with a Buffer object the filename is "file" but it works if i open it. If i use the mailgun-js Attachment Object the filename is valid like "test.pdf")
```javascript
"message": {
    "headers": {
        "to": "*********",
        "message-id": "*******@mg.*****.com",
        "from": "***** <*****@*****.com>",
        "subject": "Hello"
    },
    "attachments": [{
        "size": 214977,
        "content-type": "application/octet-stream",
        "filename": "file"
    }],
    "size": 215544
}
```

**MailgunAdapter**
(If i use the Buffer Object to send out the file is always a .bin file. If i use the mailgun-js Attachment Object the pdf looks like a valid file but i can't open it.)

```javascript
"message": {
    "headers": {
        "to": "*********",
        "message-id": "*******@mg.*****.com",
        "from": "***** <****@*****.com>",
        "subject": "Hello"
    },
    "attachments": [{
        "size": 125,
        "content-type": "application/octet-stream",
        "filename": "attachment-1.bin"
    }],
    "size": 53112
}
```

Do you guys have an idea whats wrong 🤔 ?

Thanks!

**Comment by sebsylvester** [comment]
The examples you provided made use of the ```mailgun.messages().send``` method, which I think is for plain-text emails only, whereas the MailgunAdapter uses the ```mailgun.messages().sendMime``` method, after the compiled templates have been passed to the ```mailcomposer``` which produces the MIME string. Apparently, that method does not play nice with file attachments for whatever reason.

I personally would recommend hosting any files externally and link to them from the template content. If you must use attachments, then consider using plain-text emails only, using the example code you provided.
