### ISSUE TITLE
Link in text email is URL-encoded

### ISSUE THREAD

**Issue by sjmerel** [sebsylvester/parse-server-mailgun#39]
The {{link}} value is URL-encoded, which is fine for the HTML email, but not so good for the plain-text one.  Here's what I see in my text-only email:

`To reset your password, visit this link:`
`http:&#x2F;&#x2F;localhost:1337&#x2F;parse&#x2F;apps&#x2F;TKR&#x2F;request_password_reset?token&#x3D;i65ngBIDzt5tQ02MzhnA4s8s6&amp;username&#x3D;steve%mydomain.com`

**Comment by sjmerel** [comment]
Just found the answer in #30; using {{{link}}} instead.  Probably worth mentioning this in your README. Thanks!

**Comment by sebsylvester** [comment]
You've probably overlooked it, but it's actually already in the README file => https://github.com/sebsylvester/parse-server-mailgun#sample-templates-and-template-variables

**Comment by sjmerel** [comment]
Ah, I see now… my brain didn’t notice the triple-braces there.  :-)
thanks!
-steve
