### ISSUE TITLE
Email Confirmation and Password Reset Link

### ISSUE THREAD

**Issue by fprospato** [sebsylvester/parse-server-mailgun#40]
Hello,

I have successfully implement the mailgun adapter to my parse server and users receive working emails for email confirmation and password resets. Everything is working fine, but I want to change the link they receive in these emails. As of now the link to confirm their account of reset their password shows the link to my AWS instance URL (https://ec2-xxxxxxxxx.compute.amazonaws.com:80/parse/apps/xxxxxxxx). I do not want this and instead I want the part that shows my instance's URL to be replaced with my website's URL (www.example.com) where they can still confirm their email or reset their password.

This is a question that can help so many people so any help at all will be appreciated.

**Comment by sebsylvester** [comment]
Hi, 
Check out the [email verification and password reset](https://github.com/parse-community/parse-server#email-verification-and-password-reset) section of the Parse Server docs. Then, look for the ```publicServerURL``` option. This should solve your problem.
