### ISSUE TITLE
An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.

### ISSUE THREAD

**Issue by duffek** [sebsylvester/parse-server-mailgun#44]
I recently started getting this error when trying to reset the password in our app. I saw a previous issue about this however, I believe I have all the correct info and I am still getting this issue.

**The Error Message:**
```
error: Error handling request: ParseError {
code: 1,
'An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.' } code=1, message=An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.
```
**My Index.js**

```
emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
      appName: 'MyAppName',
      fromAddress: process.env.EMAIL_FROM_ADDRESS,
      domain: process.env.EMAIL_DOMAIN,
      apiKey: process.env.EMAIL_KEY,
      publicServerURL: process.env.SERVER_URL,
      templates: {
        passwordResetEmail: {
          subject: 'Reset Your Password',
          pathPlainText: '/email/PasswordReset.txt',
          pathHtml: '/email/PasswordReset.html'  
        }
      }
    }
  },
```
Any ideas what is causing this? Thanks!

**Comment by sebsylvester** [comment]
The error was not thrown by the `parse-server-mailgun` module, but the Parse Server. From what I see, you've misplaced the `appName` parameter. It does not belong in the emailAdapter config, but a level higher. I'm getting this from the [docs](https://github.com/parse-community/parse-server#email-verification-and-password-reset), which is supposed be the first thing you check before posting issues on GitHub. If this does not solve the problem, you might want to verify the values of the env vars.

**Comment by duffek** [comment]
Thank you. I do try and review the docs. It was an easy oversight to make. Thanks for your help!
