### ISSUE TITLE
[ReferenceError: username is not defined] if used within cloudcode

### ISSUE THREAD

**Issue by mikall** [sebsylvester/parse-server-mailgun#6]
Hello,
mailgun module for system emails works fine, but when I'm trying to use mailgun module inside a cloudcode function the following error appears:

> [ReferenceError: username is not defined]

My simple main.js is:

```
const AppCache = require('parse-server/lib/cache').AppCache;
const MailgunAdapter = AppCache.get('myAppId')['userController']['adapter'];

//EMAIL TEST
Parse.Cloud.define("email", function(request, response){
        // Invoke the send method with an options object
        MailgunAdapter.send({
          templateName: 'verificationEmail',
          // Optional override of your configuration's subject
          subject: 'Important: action required',
          // Optional override of the adapter's fromAddress
          fromAddress: 'Alerts <noreply@yourapp.com>',
          recipient: 'myEmail@gmail.com',
          variables: { alert: 'New posts' } // {{alert}} will be compiled to 'New posts'
        });
});
```

I use this curl script to test the function:

```
  curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: application/json" \
  -H "X-Parse-Session-Token: r:80b274d910103d65dc7f9704e2a68829" \
  http://dev.replave.io/parse/functions/email
```

Sever stdoutput:

```
verbose: REQUEST for [POST] /parse/functions/email: {} method=POST, url=/parse/functions/email, host=dev.replave.io, user-agent=curl/7.50.1, accept=*/*, x-parse-application-id=myAppId, content-type=application/json, x-parse-session-token=r:80b274d910103d65dc7f9704e2a68829,
[ReferenceError: username is not defined]
```

Env:
Ubuntu 16.04.1 LTS
npm 3.10.8
node v4.2.6
parse-server 2.2.22

Do you have any idea on how to fit it?
Thank you

**Comment by sebsylvester** [comment]
Please check out the module's [documentation](https://www.npmjs.com/package/parse-server-mailgun#templates). In particular the code section under the 'Templates' header.  This will probably fix the issue.

**Comment by sebsylvester** [comment]
Also check out this [link](https://github.com/dan-nyanko/example-parse-server/) . It's a good example of how to use the module wit Cloud code.

**Comment by mikall** [comment]
Thank you very much! 
The last link is very helpful and shed light on my doubts!

**Comment by cheesykyle** [comment]
I recommend looking into this more. It definitely seems like a bug.

Even after moving the following into the Cloud.define function:
`const MailgunAdapter = AppCache.get('myAppId')['userController']['adapter'];`
It still returns with:
`[ReferenceError: username is not defined]`

This seems like a logical and reasonable way to call the adapter from CloudCode.

**Comment by sebsylvester** [comment]
Hi, I have just used Cloud Code to send a few test emails with custom templates, and they all arrived to my inbox.

About your error message:
```
[ReferenceError: username is not defined]
```
As stated in the docs, it's only in the password reset and address verification messages, that you can use the following template variables by default: link, appName, username and email.
When using the adapter directly, you have to pass all variables that you want to use explicitly.

If that doesn't help you, I don't know what the problem is. But it's not the module.
