### ISSUE TITLE
Variable Subject line

### ISSUE THREAD

**Issue by cheesykyle** [sebsylvester/parse-server-mailgun#7]
Does the plugin support having a variable subject line?

If so, any suggestions on implementation?

**Comment by sebsylvester** [comment]
Currently, only the custom email templates support dynamic subject lines. I'm not sure what problem you're trying to solve. But I suppose you could implement it by allowing the subject field in your configuration to accept a callback aside from just a hardcoded string. This means you will need to update the constructor. And on line #89 of src/MailgunAdapter.js you would need to change the code to something like this: 
```
message = {
   from: this.fromAddress,
   to: user.get('email'),
   subject: typeof template.subject === 'function' ? template.subject(user) : template.subject
};
```

**Comment by cheesykyle** [comment]
Exactly what I was looking for!

Do you think it would be useful to add this functionality to the adapter so that the Subject can accept either a string OR callback?

**Comment by sebsylvester** [comment]
I think it's an edge case scenario. I might incorporate that functionality with some other changes in the next update. But as I indicated already, it's not a big deal to add it yourself.
